services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # Porta para a aplicação se conectar (AMQP)
      - "15672:15672"   # Porta para acessar a interface Web (RabbitMQ Management)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest